# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc "Hello CLI"
  homepage "https://github.com/mrjefflarry/hello-cli"
  version "0.0.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.21/hello-cli_0.0.21_darwin_amd64.tar.gz"
      sha256 "d7dd2c5f4cc4dcbcf6aea2ee6f40188791853e429230ba1e6ba1546fe36a040a"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.21/hello-cli_0.0.21_darwin_arm64.tar.gz"
      sha256 "6780ed6f1cec69ed641dcf76a1fb7b5bcad512f3efe3917ca0d66b3343b959b2"

      def install
        bin.install "hello-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.21/hello-cli_0.0.21_linux_amd64.tar.gz"
      sha256 "892f816b807f2f5c1ccf68eefc72b293af7e6b94248e3720eca5bedefce65e5f"
      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.21/hello-cli_0.0.21_linux_arm64.tar.gz"
      sha256 "505de4fe0e8ff5506e9f8c285fed340a6cf99d6e104cc69025b909aeb846d733"
      def install
        bin.install "hello-cli"
      end
    end
  end

  test do
    system "#{bin}/hello-cli -v"
  end
end
