# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc "Hello CLI"
  homepage "https://github.com/mrjefflarry/hello-cli"
  version "0.0.26"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.26/hello-cli_0.0.26_darwin_amd64.tar.gz"
      sha256 "62ff05a25ee99fa65f88f5ab371f1f671ac8399e829a8936bd2b62dc71d27234"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.26/hello-cli_0.0.26_darwin_arm64.tar.gz"
      sha256 "46eb7f3efb7c87e33ee63667ce7086be6313133cfb91142b19f66442bcc3126c"

      def install
        bin.install "hello-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.26/hello-cli_0.0.26_linux_amd64.tar.gz"
      sha256 "77f0326375729d5ae2daac5bf8ffcf3779b54265f4d672356165691f18337c4f"
      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.26/hello-cli_0.0.26_linux_arm64.tar.gz"
      sha256 "204b69fb2534ba744902fd43226f1532b50a64450a46524f078727675932eb94"
      def install
        bin.install "hello-cli"
      end
    end
  end

  test do
    system "#{bin}/hello-cli -v"
  end
end
