# This file was generated by GoReleaser. DO NOT EDIT.
cask "hello-cli" do
  desc "Hello CLI"
  homepage "https://github.com/mrjefflarry/hello-cli"
  version "0.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hello-cli"

  on_macos do
    on_intel do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.17/hello-cli_0.0.17_darwin_amd64.tar.gz"
      sha256 "ea0ca044972fcf3af92d1956bef61c4fa879c0a56f33faee995033f06b3e4a22"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.17/hello-cli_0.0.17_darwin_arm64.tar.gz"
      sha256 "ee5b0107388c67fe338c7616f05fef1b467e3fceba1e6e1e4cd4b298d7a78b50"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.17/hello-cli_0.0.17_linux_amd64.tar.gz"
      sha256 "a508962ffe25b58551d8b0c774fed9c68ea865f763e32bc82d07196bbe550a12"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.17/hello-cli_0.0.17_linux_arm64.tar.gz"
      sha256 "4566e5c250974bccb82d9e6e5188bd4591570edadc0de9970390f5cd01ed51f7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'hello-cli' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hello-cli"]
    end
  end

  # No zap stanza required
end
