# This file was generated by GoReleaser. DO NOT EDIT.
cask "hello-cli" do
  desc "Hello CLI"
  homepage "https://github.com/mrjefflarry/hello-cli"
  version "0.0.21"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hello-cli"

  on_macos do
    on_intel do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.21/hello-cli_0.0.21_darwin_amd64.tar.gz"
      sha256 "d7dd2c5f4cc4dcbcf6aea2ee6f40188791853e429230ba1e6ba1546fe36a040a"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.21/hello-cli_0.0.21_darwin_arm64.tar.gz"
      sha256 "6780ed6f1cec69ed641dcf76a1fb7b5bcad512f3efe3917ca0d66b3343b959b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.21/hello-cli_0.0.21_linux_amd64.tar.gz"
      sha256 "892f816b807f2f5c1ccf68eefc72b293af7e6b94248e3720eca5bedefce65e5f"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.21/hello-cli_0.0.21_linux_arm64.tar.gz"
      sha256 "505de4fe0e8ff5506e9f8c285fed340a6cf99d6e104cc69025b909aeb846d733"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'hello-cli' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hello-cli"]
    end
  end

  # No zap stanza required
end
