# This file was generated by GoReleaser. DO NOT EDIT.
cask "hello-cli" do
  desc "Hello CLI"
  homepage "https://github.com/mrjefflarry/hello-cli"
  version "0.0.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hello-cli"

  on_macos do
    on_intel do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.15/hello-cli_0.0.15_darwin_amd64.tar.gz"
      sha256 "0b84428e6319cfafcb414a8c94e5264fc65a781d123917185c1d5a5c62191b4c"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.15/hello-cli_0.0.15_darwin_arm64.tar.gz"
      sha256 "f54768f7d54ae22c29c3f94aa2971f2b97066825b4df0c27b3405321e1db0076"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.15/hello-cli_0.0.15_linux_amd64.tar.gz"
      sha256 "332d4c6eb0538c34d821b84baaff0e791c48fddad00686adac1a3ed58484670d"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/hello-cli/releases/download/v0.0.15/hello-cli_0.0.15_linux_arm64.tar.gz"
      sha256 "2e6d851c2da9bc63edb112d0ef33e3b184b44e36178f28c7cfe257ac9f8577ba"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'hello-cli' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hello-cli"]
    end
  end

  # No zap stanza required
end
